### ISSUE TITLE
bug: Cannot read property 'ScreepsDotNet' of undefined

### ISSUE THREAD

**Issue by ffMathy** [thomasfn/ScreepsDotNet#6]
See attached:

![image](https://github.com/thomasfn/ScreepsDotNet/assets/2824010/7ea95086-ca78-4e84-ba8e-9c5231dfb6d8)

This is a screenshot from Screeps Arena.

The offending line is this:

```
exports.ScreepsDotNet.Program.Init && exports.ScreepsDotNet.Program.Init();
```

I just cloned this repo, and ran `dotnet publish -c Debug` on the solution, and then referenced the `arena` folder from Screeps.

**Comment by thomasfn** [comment]
Did you copy the files from the sample project `ScreepsDotNet`'s output? It looks like it loaded an assembly which doesn't have the `ScreepsDotNet.Program` class, which could happen if you accidentally copied the output from `ScreepsDotNet.API` or another project that doesn't have that class.

**Comment by ffMathy** [comment]
I pointed Screeps Arena to the folder `ScreepsDotNet\bin\Debug\net7.0\browser-wasm\AppBundle\arena`, so it should run the right one. If I change the `main.mjs` file directly, I can see the changes applying, so I know it's using that path.

Does that look correct to you?

**Comment by thomasfn** [comment]
That looks like the correct path. Perhaps try a release build instead of debug? Sometimes the debug builds are large and maybe the bundle size has exceeded the limit (screeps imposes a 5mb total script size limit).

**Comment by ffMathy** [comment]
I tried release builds as well. That doesn't work either. Maybe something has changed? Does it still work for you if you reclone everything from scratch?

Thank you for the help so far by the way. I am at a LAN party and would love to play Screeps using dotnet, so your swift replies are much appreciated.

**Comment by thomasfn** [comment]
Ok I managed to reproduce this on a fresh build. I'll fix it in the repo shortly but in the meantime, you can get it to work with the following small edits to the js:

`main.mjs:9` - add `'arena'` as second parameter to the constructor. e.g. `const dotNet = new DotNet(manifest, 'arena');`
`bootloader.mjs:3848-3851` - comment out lines 3848, 3850 and 3851, e.g. disable the profiling calls and logging (it was trying to making calls to the world api instead of the arena api) - all that should be left is the assignment statements to `wasmPrevAttemptBytes`, `wasmPrevAttemptModule` and `compiledModule`
